# Generated by Django 5.1.4 on 2024-12-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(default='approved', max_length=10),
        ),
    ]
